name: Android CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'

jobs:
  build-upload:
    name: Build & Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - name: Fix gradlew permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
